### PR TITLE
feat: allow extra arguments to be passed to dotnet publish command

### PR DESCRIPTION
**Pull request by ReenigneArcher**
This PR adds the ability to pass extra args to the `dotnet publish` command.

I need to be able to do this after consistently facing an error due to MSBuild.

My error: https://github.com/LizardByte/Themerr-jellyfin/actions/runs/6203819809/job/16846153379#step:4:80

Additional references:
- https://github.com/dotnet/sdk/issues/2902
- https://github.com/dotnet/aspnetcore/issues/32219#issuecomment-1405048765

### CODE REVIEW

**Comment by oddstr13** [comment]
Which additional arguments are you in need of for stable builds?

**Comment by ReenigneArcher** [comment]
@oddstr13

I believe I need to set `maxcpucount:1`. Builds are failing due a file being in use by another process. The issue started yesterday, I think something may have changed in GitHub runners.

The issue is somewhat random, but it occurs more often than not. I can get my CI to pass if I run it 5 times or so.

I figured instead of making this pr accept a specific argument, just allow it to accept anything additional to make it more flexible.

**Comment by oddstr13** [comment]
See if you can reproduce the issue locally, and if you are able to reproduce, try running with the max cpu count argument and see if that fixes it.

If it does fix it, I'll add maxcpucount:1 as a default (overridable) argument, as it is unlikely you are the only one to encounter the issue at some point. CI needs to be reliable, and potentially losing some reliability for a little speed improvement isn't worth it in my opinion.

I don't think I like the current implementation you've got here, as that would have allowed you to fix the issue in your repo, and me unlikely being made aware of the potential issue and solution. It *would* be quicker for you, but less beneficial for the rest of the community.

**Comment by ReenigneArcher** [comment]
I have reproduced in various workflows (Ubuntu GitHub runner, and building inside of docker).

Adding the `/maxcpucount:1` seems to fully resolve the issue. I ran it 5 times, and all runs succeeded (would only get success on about 15-20% of runs before). https://github.com/LizardByte/Themerr-jellyfin/actions/runs/6208779542

I can refactor this to have `maxcpucount` as an input rather than extra args (although I still think that is a good idea to have for emergency situations).

**Comment by ReenigneArcher** [comment]
Alternate PR #99

**Pull request closed without merging**
